export const LOCALIZED_STRINGS = {
  "en-US": {
    search_placeholder: "Search products…",
    active_crate: "Active Crate",
    login: "Login",
    logout: "Logout",
    all_categories: "☰ All Categories",
    for_you: "For You",
    ideal_plan: "Ideal Plan",
    cheaper: "Cheaper",
    premium: "Premium",
    fast_delivery: "Fast Delivery",
    empty_crate: "Your Crate is Empty",
    empty_crate_sub: "No products in this shopping flow version.",
    alternative_discoveries: "Alternative Discoveries",
    curation_crate_story: "Curation Crate Story",
    crate_evolution_timeline: "Cart History",
    continue_cart: "Continue your cart",
    profile_title: "Your account",
    profile_orders: "Order history",
    profile_bookmarks: "Saved products",
    profile_no_orders: "No orders yet — build a cart and checkout to see them here.",
    profile_no_bookmarks: "Tap ★ on any product card to save it here.",
    profile_start_shopping: "Start shopping",
    profile_orders_count: "Orders",
    profile_bookmarks_count: "Saved",
    profile_logout: "Sign out",
    profile_refresh: "Refresh",
    profile_order_guest: "Guest checkout",
    profile_order_live: "Kapruka order",
    profile_order_sim: "Demo order",
    profile_saved_on: "Saved",
    profile_remove_bookmark: "Remove",
    profile_ruka_tab: "For Ruka",
    profile_ruka_title: "What Ruka remembers",
    profile_ruka_desc: "This shapes city defaults, budget hints, and product ranking when you build a cart.",
    profile_ruka_empty: "Sign in and shop once — Ruka will remember your city, budget, and saved items.",
    profile_ruka_orders: "Uses {count} past order(s) for category and budget hints.",
    profile_ruka_city: "Usually delivers to {city}.",
    profile_ruka_budget: "Typical spend around LKR {budget}.",
    profile_ruka_categories: "Favourite categories: {cats}.",
    profile_ruka_saved: "Boosts {count} saved product(s) in cart picks.",
    profile_ruka_build: "Build cart with my profile",
    profile_reorder: "Reorder with Ruka",
    out_of_stock: "Out of stock",
    out_of_stock_cart_hint: "Remove out-of-stock items before checkout. Kapruka MCP rejected one or more products.",
    checkout_stock_error: "A product in your cart is out of stock on Kapruka. Remove it and try again.",
    rollback_note: "* Click any past step to rollback selections and settings to that snapshot.",
    budget_meter: "Budget Meter",
    over_budget: "Over Budget",
    healthy: "Healthy",
    drag_to_adjust: "Drag to Adjust Budget Limit",
    items_subtotal: "Items Subtotal",
    delivery_fee: "Delivery Fee",
    total_price: "Total Price",
    proceed_to_checkout: "Proceed to Checkout",
    control_center: "Control Center",
    curation_actions: "Curation Actions",
    personalization_delivery: "Personalization & Delivery",
    language_context: "Language Context",
    make_cheaper: "Make Cheaper",
    upgrade_premium: "Upgrade Premium",
    today_delivery: "Today Delivery",
    gift_mode: "Gift Mode",
    sinhala: "Sinhala",
    tanglish: "Tanglish",
    optimize: "Optimize",
    surprise_me: "Surprise Me",
    remove: "Remove",
    replace: "Replace",
    qty: "Qty",
    curation_note: "Curation Note",
    add_to_crate: "Add to Crate +",
    search_catalog: "Search catalog...",
    alternative_items: "Alternative items:",
    searching_catalog: "Searching catalog...",
    no_items_found: "No items found",
    review_checkout: "Review & Checkout",
    checkout_sub: "Establish your Kapruka guest order. No account registration is required.",
    sender_details: "1. Sender Details",
    your_full_name: "Your Full Name",
    recipient_details: "2. Recipient Details",
    name: "Name",
    mobile_phone: "Mobile Phone",
    delivery_gift_msg: "3. Delivery & Gift Message",
    delivery_city: "Delivery City",
    preferred_date: "Preferred Date",
    street_address: "Street Address",
    instructions_opt: "Instructions (Optional)",
    gift_card_msg_opt: "Gift Card Message (Optional)",
    total_with_delivery: "Total (with delivery)",
    cancel: "Cancel",
    proceed_to_payment: "Continue to Payment",
    generating_secure_checkout: "Generating Secure Checkout…",
    preparing_order: "Preparing Order...",
    order_success: "Order Created Successfully!",
    order_success_sub: "Your guest-checkout order has been established on Kapruka.",
    invoice_title: "Kapruka Flow Invoice",
    order_ref: "Order Ref:",
    date: "Date:",
    sender: "Sender:",
    recipient: "Recipient:",
    phone: "Phone:",
    city: "City:",
    deliver_to: "Deliver To:",
    item_description: "Item Description",
    qty_header: "Qty",
    total_header: "Total",
    final_total: "Final Total:",
    simulated_checkout_note: "Simulated Checkout Link generated for development.",
    complete_payment: "Pay on Kapruka",
    close_return: "Close & Return",
    guest_user: "Guest User",
    alert_no_crate: "No active curation crate found. Please enter your shopping request in the prompt below first!",
    curation_in_progress: "Curation in Progress",
    step_understanding: "Understanding",
    step_finding: "Finding Products",
    step_budget: "Budget Planning",
    step_delivery: "Delivery Validation",
    step_cart: "Cart Building",
    starting: "Starting",
    compiled: "Compiled",
    ready: "Ready",
    mcp_live: "Live from Kapruka MCP",
    mcp_connecting: "Connecting to Kapruka MCP...",
    mcp_status_ready: "Ready",
    mcp_status_connecting: "Connecting",
    mcp_status_live: "Live",
    mcp_status_unavailable: "Unavailable",
    mcp_demo_still_available: "Demo still available",
    waiting_pipeline: "Running AI shopping pipeline...",
    header_tagline: "Tell us what you want. We'll build the plan.",
    new_flow: "New Flow",
    plan_changes: "Plan Changes",
    added: "Added",
    removed: "Removed",
    checkout_failed: "Order creation failed",
    checkout_failed_sub: "Kapruka could not create this order. Check delivery city, date, and product availability.",
    pipeline_error: "Failed to build your shopping flow. Please try again.",
    pipeline_timeout: "Request timed out — Kapruka MCP may be slow. Try again.",
    network_fail: "Network error — check your connection and try again.",
    no_products: "No matching products found on Kapruka. Please check your query or try suggestions like 'cakes', 'chocolates', 'flowers', or 'groceries'.",
    suggested_addons: "Suggested add-ons",
    suggested_addons_hint: "Want more? Add any of these — higher or lower priced. It's your call, even if it nudges you over budget.",
    lower_price: "Lower price",
    higher_price: "Higher price",
    over_budget_hint: "You're over your budget. Remove an item, swap in a lower-priced suggestion, or raise the slider. Totally your call.",
    chat_placeholder: "Tell Ruka what to change (e.g. 'add chocolates', 'make it cheaper')…",
    qr_add_choc: "Add chocolates",
    qr_add_flowers: "Add flowers",
    qr_add_cake: "Add cake",
    qr_add_groceries: "Add groceries",
    chat_reply_cheaper: "Done, switched to the value-focused plan. 💸",
    chat_reply_premium: "Here's the premium plan with a richer mix. ✨",
    chat_reply_fast: "Switched to the fastest-delivery plan. ⚡",
    chat_reply_budget: "Re-balanced everything to fit LKR {budget}. ✅",
    chat_reply_city: "Updated delivery to {city}. 🚚",
    chat_reply_added: "Added {name} to your cart. 🛒",
    chat_reply_add_fail: "I couldn't find '{query}' in Kapruka's catalog right now. Want to try another item?",
    chat_reply_removed: "Removed {name}. 👍",
    chat_reply_remove_fail: "I couldn't find '{query}' in your current cart. Which item should I remove?",
    chat_reply_gift: "Got it, I'll treat this as a gift. 🎁",
    chat_reply_researching: "Let me search Kapruka's catalog for that…",
    chat_reply_reorder: "Rebuilding from your order history…",
    chat_reply_saved_added: "Added your saved items: {names}. ★",
    chat_reply_saved_none: "You don't have any saved items yet — tap ★ on a product card first.",
    agent_profile_note: "Used your profile ({summary}) to personalize picks.",
    agent_profile_orders: "{count} past orders",
    agent_profile_saved: "{count} saved items",
    agent_profile_city: "usually {city}",
    qr_reorder: "Reorder favourites",
    qr_add_saved: "Add saved items",
    qr_deliver_city: "Deliver to {city}",
    insight_orders: "{count} orders",
    insight_saved: "{count} saved",
    insight_usual_city: "Usually {city}",
    chat_clarify: "I can change the budget, switch plans, add or remove items, or change delivery. Try 'add chocolates under 3000', 'make it cheaper', or 'deliver to Galle'.",
    mcp_tools_title: "Kapruka MCP tools used",
    mcp_calls: "calls",
    run_demo: "▶ Run Demo",
    picked_for_you: "Picked for you",
    demo_hint: "Loads the canonical demo prompt — press Build My Cart when ready.",
    agent_name: "Ruka",
    agent_role: "Your Kapruka shopping buddy",
    agent_greeting: "Hi, I'm Ruka 🌸 your personal Kapruka shopper. Tell me who it's for and your budget, and I'll build the perfect cart from Kapruka's live catalog.",
    agent_reply_intro: "All set! Here's what I pulled together from Kapruka's live catalog 👇",
    agent_budget_inferred: "You didn't set a budget, so I went with LKR {budget}. Drag the slider and I'll rebalance instantly. What's your real limit?",
    agent_gift_note: "Looks like a gift{recipient}, so I leaned into things they'll love. 🎁",
    agent_occasion_note: "Happy {occasion}! I tuned the picks for the occasion. 🎉",
    agent_pick_one: "Pick a plan (Ideal, Cheaper, Premium or Fast) and I'll take you straight to checkout. 🛒",
    agent_thinking: "Ruka is thinking…",
    flow_error_title: "Something went wrong",
    dismiss: "Dismiss",
    share_flow: "Share Flow",
    link_copied: "Link copied!",
    view_on_kapruka: "View on Kapruka",
    mcp_catalog_count: "Kapruka MCP Catalog",
    products_live: "live products",
    order_ref_note: "This is your Kapruka checkout reference. Complete payment in the browser to receive your final order number by email.",
    powered_by_mcp: "Order created via Kapruka MCP",
    email_optional: "Email (optional)",
    create_account_opt: "Create my Kapruka Flow account so I can track this order (optional)",
    choose_password: "Choose a password",
    
    // Intent Canvas additions
    intelligent_ai_curation: "Intelligent AI Curation",
    what_do_you_want: "Tell me what you need.",
    what_do_you_want_line2: "I'll build the cart.",
    intent_desc: "Describe your shopping goal. We'll compose the perfect cart.",
    build_my_cart: "Build My Cart",
    voice_intent: "Voice Intent",
    listening: "Listening...",
    input_placeholder: "I need tea bags under 5000 LKR for tomorrow...",
    compose: "Compose",
    quick_suggestions: "Quick Suggestions",
    search_btn: "Search",
    account_label: "Account",
    hello_label: "Hello",
    trending: "Trending",
    live_badge: "Live",
    reset_label: "Reset",
    browse_categories: "Browse Kapruka categories",
    loading: "Loading…",
    cart_item_singular: "item",
    cart_item_plural: "items",
    welcome_back: "Welcome back",
    history_note: "AI uses your order history",
    try_again: "Try Again",
    general_category: "General",
    lang_english: "English",
    lang_sinhala: "සිංහල (Sinhala)",
    lang_tanglish: "Tanglish (Sri Lanka)",
    qs_monthly_label: "Monthly Shopping",
    qs_monthly_text: "groceries under 20000 LKR",
    qs_today_label: "Need Something Today",
    qs_today_text: "I need groceries delivered today to Colombo",
    qs_gift_label: "Gift Crate",
    qs_gift_text: "My sister graduated, need a gift hamper under 15000 LKR",
    qs_surprise_label: "Surprise Me",
    qs_surprise_text: "Surprise me with tea and cake hamper",
    qs_build_label: "Build My Cart",
    qs_build_text: "Build my cart with tea time snacks for team",
    qs_budget_label: "Budget Shopping",
    qs_budget_text: "Need dinner budget shopping under 10000 LKR",
    qs_custom_label: "Custom Request",
    qs_custom_text: "Custom request for fresh fruits and chocolates",
    mcp_tool_search: "Product search",
    mcp_tool_details: "Product details",
    mcp_tool_cities: "Delivery cities",
    mcp_tool_delivery: "Delivery check",
    mcp_tool_categories: "Categories",
    mcp_tool_order: "Order creation",
    ai_insights_title: "AI Insights",
    detected_intent: "Detected intent",
    insight_budget: "Budget",
    insight_remaining: "Remaining",
    insight_delivery_today: "Tomorrow",
    insight_delivery_fast: "Fast",
    insight_delivery_standard: "Standard",
    // Cart history & budget meter
    compare_versions: "⚖️ Compare Versions",
    budget_spent: "{amount} spent",
    budget_limit_label: "Limit {amount}",
    step_label: "Step {n}",
    step_current: "(Current)",
    cart_history_spent: "Spent: Rs {amount}",
    cart_history_items: "{n} items",
    // Chat suggestions
    chat_suggested: "Suggested",
    suggestion_add_chocolates: "Add chocolates",
    suggestion_add_flowers: "Add flowers",
    suggestion_add_cake: "Add a cake",
    suggestion_gift_wrap: "Gift wrap for {occasion}",
    suggestion_cut_budget: "Cut to Rs {amount}",
    suggestion_upgrade_premium: "Go premium Rs {amount}",
    suggestion_same_day: "Same-day delivery",
    suggestion_change_city: "Ship to {city}",
    suggestion_rebuild: "Rebuild cart",
    // Profile order fields
    order_recipient: "Recipient",
    order_city: "City",
    order_date: "Date",
    order_total: "Total",
    // Checkout validation messages
    checkout_sender_required: "Sender name is required",
    checkout_recipient_required: "Recipient name is required",
    checkout_phone_required: "Mobile number is required",
    checkout_phone_invalid: "Enter a valid Sri Lanka mobile number (07xxxxxxxx)",
    checkout_email_invalid: "Enter a valid email address",
    checkout_city_required: "Delivery city is required",
    checkout_date_required: "Delivery date is required",
    checkout_date_past: "Please select a future delivery date",
    checkout_cart_empty: "Your cart is empty",
    checkout_price_changed: "Some item prices changed — please review your cart.",
    checkout_item_unavailable: "One or more items are now out of stock.",
    checkout_processing: "Processing your order…",
    checkout_order_confirmed: "Order Confirmed!",
    checkout_save_ref: "Save your order reference",
    checkout_track_order: "Track on Kapruka.com",
    checkout_payment_failed: "Payment failed. Your cart is saved — try again.",
    checkout_duplicate_prevented: "Your order is already being processed.",
    // Pluralization
    cart_item_count_one: "{n} item",
    cart_item_count_many: "{n} items",
    cart_empty: "Your cart is empty",
    // ── Gaps & Localization additions ───────────────────────────────
    ai_pick: "✨ AI Pick",
    for_recipient: " for {recipient}",
    within_budget: " within LKR {budget}",
    ruka_greeting_curated: "I curated the perfect {categories}{recipient}{occasion}{budget}. 🎁 Switch plans or ask me anything!",
    ruka_greeting_prompt: "Here's your curated cart for \"{prompt}\"{budget}. Anything to tweak?",
    // Category labels
    category_flowers: "Flowers",
    category_cakes: "Cakes",
    category_groceries: "Groceries",
    category_chocolates: "Chocolates",
    category_toys: "Toys",
    category_gifts: "Gifts",
    category_hampers: "Hampers",
    category_books: "Books",
    category_electronics: "Electronics",
    category_clothing: "Clothing",
    category_cosmetics: "Cosmetics",
    // DNA chips: Occasions
    dna_occasion_birthday: "Birthday",
    dna_occasion_anniversary: "Anniversary",
    dna_occasion_wedding: "Wedding",
    dna_occasion_valentine: "Valentine's",
    dna_occasion_mothers_day: "Mother's Day",
    dna_occasion_fathers_day: "Father's Day",
    dna_occasion_christmas: "Christmas",
    dna_occasion_new_year: "New Year",
    dna_occasion_graduation: "Graduation",
    dna_occasion_farewell: "Farewell",
    dna_occasion_get_well: "Get Well",
    dna_occasion_thank_you: "Thank You",
    // DNA chips: Recipients
    dna_recipient_amma: "For Amma",
    dna_recipient_mother: "For Mum",
    dna_recipient_father: "For Dad",
    dna_recipient_thaththa: "For Thaththa",
    dna_recipient_sister: "For Sister",
    dna_recipient_brother: "For Brother",
    dna_recipient_friend: "For Friend",
    dna_recipient_colleague: "For Colleague",
    dna_recipient_teacher: "For Teacher",
    dna_recipient_girlfriend: "For Her",
    dna_recipient_boyfriend: "For Him",
    dna_recipient_partner: "For Partner",
    dna_recipient_baby: "For Baby",
    dna_recipient_kids: "For Kids",
    dna_recipient_grandma: "For Grandma",
    dna_recipient_grandfather: "For Grandpa",
    // DNA chips: Sentiments
    dna_sentiment_heartfelt: "Heartfelt",
    dna_sentiment_premium: "Premium",
    dna_sentiment_luxury: "Luxury",
    dna_sentiment_budget: "Value Pick",
    dna_sentiment_popular: "Popular",
    dna_sentiment_fresh: "Fresh",
    dna_sentiment_classic: "Classic",
    dna_sentiment_surprise: "Surprise",
    dna_sentiment_romantic: "Romantic",
    dna_sentiment_healthy: "Healthy",
    dna_sentiment_traditional: "Traditional",
    dna_sentiment_best_seller: "Best Seller",
    dna_sentiment_handpicked: "Handpicked"
  },
  "si-LK": {
    search_placeholder: "භාණ්ඩ සොයන්න..",
    active_crate: "සක්‍රීය කරත්තය",
    login: "ඇතුල් වන්න",
    logout: "පිටවන්න",
    all_categories: "☰ සියලුම කාණ්ඩ",
    for_you: "ඔබ සඳහා",
    ideal_plan: "හොඳම සැලැස්ම",
    cheaper: "ලාභදායී",
    premium: "ප්‍රිමියම්",
    fast_delivery: "ඉක්මන් බෙදාහැරීම",
    empty_crate: "ඔබගේ කරත්තය හිස්ය",
    empty_crate_sub: "මෙම සාප්පු සවාරි අනුවාදයේ භාණ්ඩ නොමැත.",
    alternative_discoveries: "විකල්ප සොයාගැනීම්",
    curation_crate_story: "කරත්තයේ නිර්දේශ විස්තරය",
    crate_evolution_timeline: "කරත්ත ඉතිහාසය",
    continue_cart: "ඔබේ කරත්තය දිගටම",
    profile_title: "ඔබේ ගිණුම",
    profile_orders: "ඇණවුම් ඉතිහාසය",
    profile_bookmarks: "සුරකින ලද භාණ්ඩ",
    profile_no_orders: "තවම ඇණවුම් නැත — කරත්තයක් සාදා ගෙවීමෙන් මෙහි පෙනේ.",
    profile_no_bookmarks: "භාණ්ඩ කාඩ්පතේ ★ ඔබන්න සුරකින්න.",
    profile_start_shopping: "සාප්පු යන්න",
    profile_orders_count: "ඇණවුම්",
    profile_bookmarks_count: "සුරකින ලද",
    profile_logout: "පිටවීම",
    profile_refresh: "නැවත ලෝඩ්",
    profile_order_guest: "අමුත්තා ගෙවීම",
    profile_order_live: "කප්රුක ඇණවුම",
    profile_order_sim: "ආදර්ශන ඇණවුම",
    profile_saved_on: "සුරකින ලදී",
    profile_remove_bookmark: "ඉවත් කරන්න",
    profile_ruka_tab: "රුක සඳහා",
    profile_ruka_title: "රුක මතක තබාගන්නේ",
    profile_ruka_desc: "කරත්තයක් සාදන විට නගරය, අයවැය සහ භාණ්ඩ ශ්‍රේණිගත කිරීම මෙයින් බලපායි.",
    profile_ruka_empty: "ඇතුල් වී එක් ඇණවුමක් කරන්න — රුක ඔබේ නගරය, අයවැය සහ සුරකින ලද භාණ්ඩ මතක තබාගනී.",
    profile_ruka_orders: "ඇණවුම් {count}ක් අනුව කාණ්ඩ සහ අයවැය ඉඟි භාවිත කරයි.",
    profile_ruka_city: "සාමාන්‍යයෙන් {city} වෙත බෙදාහරියි.",
    profile_ruka_budget: "සාමාන්‍ය වියදම LKR {budget} පමණ.",
    profile_ruka_categories: "ප්‍රියතම කාණ්ඩ: {cats}.",
    profile_ruka_saved: "සුරකින ලද භාණ්ඩ {count}ක් තෝරා ගැනීමේදී උසස් කරයි.",
    profile_ruka_build: "මගේ පැතිකඩ භාවිතයෙන් කරත්තය සාදන්න",
    profile_reorder: "රුක සමඟ නැවත ඇණවුම් කරන්න",
    out_of_stock: "තොග නැත",
    out_of_stock_cart_hint: "ගෙවීමට පෙර තොග නැති භාණ්ඩ ඉවත් කරන්න.",
    checkout_stock_error: "කරත්තයේ භාණ්ඩයක් කප්රුක වෙත තොග නැත. ඉවත් කර නැවත උත්සාහ කරන්න.",
    rollback_note: "* පෙර පියවරකට ආපසු යාමට එම පියවර මත ක්ලික් කරන්න.",
    budget_meter: "අයවැය මීටරය",
    over_budget: "අයවැය ඉක්මවා ඇත",
    healthy: "හොඳයි",
    drag_to_adjust: "අයවැය සීමාව වෙනස් කිරීමට අදින්න",
    items_subtotal: "භාණ්ඩ එකතුව",
    delivery_fee: "බෙදාහැරීමේ ගාස්තුව",
    total_price: "මුළු මුදල",
    proceed_to_checkout: "ගෙවීම් සඳහා ඉදිරියට යන්න",
    control_center: "පාලන මධ්‍යස්ථානය",
    curation_actions: "නිර්දේශ ක්‍රියාකාරකම්",
    personalization_delivery: "පුද්ගලීකරණය සහ බෙදාහැරීම",
    language_context: "භාෂා සන්දර්භය",
    make_cheaper: "අඩු මිල කරන්න",
    upgrade_premium: "ප්‍රිමියම් කරන්න",
    today_delivery: "අදම බෙදන්න",
    gift_mode: "තෑගි ක්‍රමය",
    sinhala: "සිංහල",
    tanglish: "තංග්ලිෂ්",
    optimize: "ප්‍රශස්ත කරන්න",
    surprise_me: "පුදුම කරන්න",
    remove: "ඉවත් කරන්න",
    replace: "වෙනස් කරන්න",
    qty: "ප්‍රමාණය",
    curation_note: "නිර්දේශ සටහන",
    add_to_crate: "කරත්තයට එක් කරන්න +",
    search_catalog: "නාමාවලිය සොයන්න...",
    alternative_items: "විකල්ප භාණ්ඩ:",
    searching_catalog: "සොයමින් පවතී...",
    no_items_found: "භාණ්ඩ හමු නොවීය",
    review_checkout: "සමාලෝචනය සහ ගෙවීම",
    checkout_sub: "ඔබගේ කප්රුක අමුත්තන්ගේ ඇණවුම සකස් කරන්න. ගිණුම් ලියාපදිංචිය අවශ්‍ය නොවේ.",
    sender_details: "1. යවන්නාගේ විස්තර",
    your_full_name: "ඔබගේ සම්පූර්ණ නම",
    recipient_details: "2. ලබන්නාගේ විස්තර",
    name: "නම",
    mobile_phone: "ජංගම දුරකථනය",
    delivery_gift_msg: "3. බෙදාහැරීම සහ තෑගි පණිවිඩය",
    delivery_city: "බෙදාහරින නගරය",
    preferred_date: "කැමති දිනය",
    street_address: "ලිපිනය",
    instructions_opt: "උපදෙස් (විකල්ප)",
    gift_card_msg_opt: "තෑගි පණිවිඩය (විකල්ප)",
    total_with_delivery: "මුළු මුදල (බෙදාහැරීම සමඟ)",
    cancel: "අවලංගු කරන්න",
    proceed_to_payment: "ගෙවීමට ඉදිරියට",
    generating_secure_checkout: "ආරක්ෂිත ගෙවීම් සබැඳිය සකසමින්…",
    preparing_order: "ඇණවුම සූදානම් කරමින්...",
    order_success: "ඇණවුම සාර්ථකව නිර්මාණය කරන ලදී!",
    order_success_sub: "ඔබගේ අමුත්තන්ගේ ඇණවුම කප්රුක හි සාර්ථකව සටහන් කර ඇත.",
    invoice_title: "කප්රුක ෆ්ලෝ ඉන්වොයිසිය",
    order_ref: "ඇණවුම් අංකය:",
    date: "දිනය:",
    sender: "යවන්නා:",
    recipient: "ලබන්නා:",
    phone: "දුරකථනය:",
    city: "නගරය:",
    deliver_to: "බෙදාහැරිය යුතු ස්ථානය:",
    item_description: "භාණ්ඩ විස්තරය",
    qty_header: "ප්‍රමාණය",
    total_header: "එකතුව",
    final_total: "අවසන් මුළු එකතුව:",
    simulated_checkout_note: "සංවර්ධන කටයුතු සඳහා සමාකරණ ගෙවීම් සබැඳියක් සාදන ලදී.",
    complete_payment: "කප්රුක වෙත ගෙවන්න",
    close_return: "වසා ආපසු යන්න",
    guest_user: "අමුත්තා",
    alert_no_crate: "සක්‍රීය කරත්තයක් හමු නොවීය. කරුණාකර පළමුව පහතින් ඔබගේ සාප්පු සවාරි ඉල්ලීම ඇතුළත් කරන්න!",
    curation_in_progress: "නිර්දේශ සකස් කරමින් පවතී",
    step_understanding: "අවබෝධ කර ගැනීම",
    step_finding: "භාණ්ඩ සෙවීම",
    step_budget: "අයවැය සැලසුම් කිරීම",
    step_delivery: "බෙදාහැරීම තහවුරු කිරීම",
    step_cart: "කරත්තය සකස් කිරීම",
    starting: "ආරම්භ කිරීම",
    compiled: "සකස් කරන ලදී",
    ready: "සූදානම්",
    mcp_live: "කප්රුක MCP වෙතින් සජීවී",
    mcp_connecting: "කප්රුක MCP වෙත සම්බන්ධ වෙමින්...",
    mcp_status_ready: "සූදානම්",
    mcp_status_connecting: "සම්බන්ධ වෙමින්",
    mcp_status_live: "සජීවී",
    mcp_status_unavailable: "ලබා ගත නොහැක",
    mcp_demo_still_available: "ආදර්ශනය තවමත් ලබා ගත හැක",
    waiting_pipeline: "AI සාප්පු සැලසුම සකසමින්...",
    header_tagline: "ඔබට අවශ්‍ය දේ කියන්න. අපි සැලසුම සාදන්නෙමු.",
    new_flow: "නව සැලසුම",
    plan_changes: "සැලසුම් වෙනස්කම්",
    added: "එකතු කළ",
    removed: "ඉවත් කළ",
    checkout_failed: "ඇණවුම සාදා ගැනීම අසාර්ථකයි",
    checkout_failed_sub: "කප්රුක මෙම ඇණවුම සාදා ගත නොහැක. බෙදාහැරීමේ නගරය, දිනය සහ භාණ්ඩ ලබා ගත හැකි බව පරීක්ෂා කරන්න.",
    pipeline_error: "සාප්පු සැලසුම සකස් කිරීම අසාර්ථක විය. නැවත උත්සාහ කරන්න.",
    pipeline_timeout: "ඉල්ලීම කල් ඉකුත් විය — කප්රුක MCP මන්දගාමී විය හැක. නැවත උත්සාහ කරන්න.",
    network_fail: "ජාල දෝෂයක් — සම්බන්ධතාව පරීක්ෂා කර නැවත උත්සාහ කරන්න.",
    no_products: "ගැලපෙන භාණ්ඩ කිසිවක් හමු නොවීය. කේක්, චොකලට්, මල් හෝ සිල්ලර බඩු වැනි යෝජනාවක් භාවිතයෙන් නැවත උත්සාහ කරන්න.",
    suggested_addons: "යෝජිත අමතර අයිතම",
    suggested_addons_hint: "තවත් ඕනෑද? මේවායින් කැමති ඒවා එකතු කරන්න — වැඩි හෝ අඩු මිල. අයවැය ඉක්මවුවත් ඔබේ තීරණයයි.",
    lower_price: "අඩු මිල",
    higher_price: "වැඩි මිල",
    over_budget_hint: "ඔබ අයවැය ඉක්මවා ඇත. අයිතමයක් ඉවත් කරන්න, අඩු මිල යෝජනාවක් එක් කරන්න, නැතහොත් slider එක ඉහළ දමන්න. ඔබේ තීරණයයි.",
    chat_placeholder: "වෙනස් කළ යුතු දේ රුකට කියන්න (උදා: 'add chocolates', 'බජට් එක 20000 කරන්න')…",
    qr_add_choc: "චොකලට් එක් කරන්න",
    qr_add_flowers: "මල් එක් කරන්න",
    qr_add_cake: "කේක් එක් කරන්න",
    qr_add_groceries: "සිල්ලර බඩු එක් කරන්න",
    chat_reply_cheaper: "හරි, වටිනාකම අනුව සැලසුමට මාරු කළා. 💸",
    chat_reply_premium: "මෙන්න වඩාත් පොහොසත් ප්‍රිමියම් සැලසුම. ✨",
    chat_reply_fast: "වේගවත්ම බෙදාහැරීමේ සැලසුමට මාරු කළා. ⚡",
    chat_reply_budget: "සියල්ල LKR {budget} ට ගැලපෙන ලෙස නැවත සකස් කළා. ✅",
    chat_reply_city: "බෙදාහැරීම {city} ට යාවත්කාලීන කළා. 🚚",
    chat_reply_added: "{name} ඔබගේ කරත්තයට එක් කළා. 🛒",
    chat_reply_add_fail: "'{query}' දැන් කප්රුක නාමාවලියේ සොයාගත නොහැක. වෙනත් අයිතමයක් උත්සාහ කරමුද?",
    chat_reply_removed: "{name} ඉවත් කළා. 👍",
    chat_reply_remove_fail: "ඔබගේ කරත්තයේ '{query}' සොයාගත නොහැක. කුමන අයිතමය ඉවත් කරන්නද?",
    chat_reply_gift: "හරි, මෙය තෑග්ගක් ලෙස සලකමි. 🎁",
    chat_reply_researching: "කප්රුක නාමාවලියෙන් සොයා බලන්නම්…",
    chat_reply_reorder: "ඔබගේ ඇණවුම් ඉතිහාසය අනුව නැවත සාදමින්…",
    chat_reply_saved_added: "ඔබගේ සුරකින ලද භාණ්ඩ එක් කළා: {names}. ★",
    chat_reply_saved_none: "තවම සුරකින ලද භාණ්ඩ නැත — භාණ්ඩ කාඩ්පතේ ★ ඔබන්න.",
    agent_profile_note: "ඔබගේ පැතිකඩ ({summary}) භාවිතයෙන් තෝරා ගැනීම් පුද්ගලීකරණය කළා.",
    agent_profile_orders: "ඇණවුම් {count}",
    agent_profile_saved: "සුරකින ලද {count}",
    agent_profile_city: "සාමාන්‍යයෙන් {city}",
    qr_reorder: "ප්‍රියතම නැවත ඇණවුම",
    qr_add_saved: "සුරකින ලද භාණ්ඩ එක් කරන්න",
    qr_deliver_city: "{city} වෙත බෙදන්න",
    insight_orders: "ඇණවුම් {count}",
    insight_saved: "සුරකින ලද {count}",
    insight_usual_city: "සාමාන්‍යයෙන් {city}",
    chat_clarify: "මට අයවැය වෙනස් කිරීම, සැලසුම් මාරු කිරීම, අයිතම එක් කිරීම/ඉවත් කිරීම, හෝ බෙදාහැරීම වෙනස් කළ හැක. 'add chocolates under 3000', 'make it cheaper', හෝ 'deliver to Galle' උත්සාහ කරන්න.",
    mcp_tools_title: "භාවිත කළ කප්රුක MCP මෙවලම්",
    mcp_calls: "ඇමතුම්",
    run_demo: "▶ ආදර්ශනය ආරම්භ කරන්න",
    picked_for_you: "ඔබ වෙනුවෙන් තෝරාගත්",
    demo_hint: "අලුත්ද? රුක තත්පර කිහිපයකින් තෑග්ගක් සැලසුම් කරනවා බලන්න.",
    agent_name: "රුක",
    agent_role: "ඔබගේ කප්රුක සාප්පු සහායක",
    agent_greeting: "ආයුබෝවන්, මම රුක 🌸 ඔබගේ පෞද්ගලික කප්රුක සාප්පුකරු. කාටද, අයවැය කීයද කියන්න, මම කප්රුක සජීවී නාමාවලියෙන් හොඳම කරත්තය හදන්නම්.",
    agent_reply_intro: "හරි! කප්රුක සජීවී නාමාවලියෙන් මම සකස් කළ දේ මෙන්න 👇",
    agent_budget_inferred: "ඔබ අයවැයක් දුන්නේ නැහැ, ඒ නිසා LKR {budget} ක් තේරුවා. slider එක ගෙනියන්න, මම වහාම නැවත සකසන්නම්. ඇත්ත සීමාව කීයද?",
    agent_gift_note: "මේක තෑග්ගක් වගේ{recipient}, ඒ නිසා ඔවුන් කැමති දේවල් තේරුවා. 🎁",
    agent_occasion_note: "සුභ {occasion}! අවස්ථාවට ගැලපෙන ලෙස තේරීම් සකස් කළා. 🎉",
    agent_pick_one: "සැලසුමක් තෝරන්න (Ideal, Cheaper, Premium හෝ Fast), මම ඔබව කෙලින්ම checkout එකට ගෙනියන්නම්. 🛒",
    agent_thinking: "රුක හිතනවා…",
    flow_error_title: "යමක් වැරදී ඇත",
    dismiss: "ඉවත් කරන්න",
    share_flow: "සැලසුම බෙදාගන්න",
    link_copied: "සබැඳිය පිටපත් විය!",
    view_on_kapruka: "කප්රුක වෙත බලන්න",
    mcp_catalog_count: "කප්රුක MCP නාමාවලිය",
    products_live: "සජීවී භාණ්ඩ",
    order_ref_note: "මෙය ඔබගේ කප්රුක ගෙවීම් යොමුවයි. අවසාන ඇණවුම් අංකය ඊමේල් මගින් ලැබෙනු ඇත.",
    powered_by_mcp: "කප්රුක MCP හරහා ඇණවුම සාදන ලදී",
    email_optional: "ඊමේල් (අත්‍යවශ්‍ය නොවේ)",
    create_account_opt: "මෙම ඇණවුම නිරීක්ෂණය කිරීමට මගේ කප්රුක Flow ගිණුම සාදන්න (අත්‍යවශ්‍ය නොවේ)",
    choose_password: "මුරපදයක් තෝරන්න",
    
    // Intent Canvas additions
    intelligent_ai_curation: "බුද්ධිමත් AI නිර්දේශනය",
    what_do_you_want: "ඔබට අවශ්‍ය දේ කියන්න.",
    what_do_you_want_line2: "මම කරත්තය හදන්නම්.",
    intent_desc: "ඔබගේ සාප්පු අවශ්‍යතාව විස්තර කරන්න. අපි හොඳම කරත්තය සාදන්නෙමු.",
    build_my_cart: "කරත්තය හදන්න",
    voice_intent: "හඬ සහාය",
    listening: "ශ්‍රවණය කරමින්...",
    input_placeholder: "මට හෙටට තේ කොළ පැකට් 5000 කට වඩා අඩු මිලකට අවශ්‍යයි...",
    compose: "සකසන්න",
    quick_suggestions: "ඉක්මන් යෝජනා",
    search_btn: "සොයන්න",
    account_label: "ගිණුම",
    hello_label: "ආයුබෝවන්",
    trending: "ජනප්‍රිය",
    live_badge: "සජීවී",
    reset_label: "නැවත සකසන්න",
    browse_categories: "කප්රුක කාණ්ඩ බලන්න",
    loading: "පූරණය වෙමින්…",
    cart_item_singular: "භාණ්ඩය",
    cart_item_plural: "භාණ්ඩ",
    welcome_back: "නැවත සාදරයෙන්",
    history_note: "AI ඔබගේ පෙර ඇණවුම් ඉතිහාසය භාවිතා කරයි",
    try_again: "නැවත උත්සාහ කරන්න",
    general_category: "සාමාන්‍ය",
    lang_english: "English",
    lang_sinhala: "සිංහල (Sinhala)",
    lang_tanglish: "Tanglish (Sri Lanka)",
    qs_monthly_label: "මාසික සාප්පු",
    qs_monthly_text: "රුපියල් 20000 ට අඩු බඩු සාප්පු",
    qs_today_label: "අද අවශ්‍ය දෙයක්",
    qs_today_text: "අද කොළඹට බඩු බෙදාහැරීම අවශ්‍යයි",
    qs_gift_label: "තෑගි කරත්තය",
    qs_gift_text: "අක්කා උපාධිය ගත්තා, රු 15000 ට අඩු තෑගි කලඹක්",
    qs_surprise_label: "පුදුම කරන්න",
    qs_surprise_text: "තේ සහ කේක් කලඹකින් පුදුම කරන්න",
    qs_build_label: "කරත්තය හදන්න",
    qs_build_text: "කණ්ඩායමට තේ කාල ස්නැක්ස් සහිත කරත්තයක්",
    qs_budget_label: "අයවැය අනුව",
    qs_budget_text: "රු 10000 ට අඩු රාත්‍රී ආහාර සාප්පු",
    qs_custom_label: "විශේෂ ඉල්ලීම",
    qs_custom_text: "නැවුම් පළතුරු සහ චොකලට් විශේෂ ඉල්ලීම",
    mcp_tool_search: "භාණ්ඩ සෙවීම",
    mcp_tool_details: "භාණ්ඩ විස්තර",
    mcp_tool_cities: "බෙදාහැරීමේ නගර",
    mcp_tool_delivery: "බෙදාහැරීම පරීක්ෂාව",
    mcp_tool_categories: "කාණ්ඩ",
    mcp_tool_order: "ඇණවුම සෑදීම",
    ai_insights_title: "AI අවබෝධය",
    detected_intent: "හඳුනාගත් අවශ්‍යතාව",
    insight_budget: "අයවැය",
    insight_remaining: "ඉතිරිය",
    insight_delivery_today: "හෙට",
    insight_delivery_fast: "ඉක්මන්",
    insight_delivery_standard: "සාමාන්‍ය",
    // Cart history & budget meter
    compare_versions: "⚖️ සංසන්දනය",
    budget_spent: "{amount} වැය කළා",
    budget_limit_label: "සීමාව {amount}",
    step_label: "පියවර {n}",
    step_current: "(වත්මන්)",
    cart_history_spent: "වැය: රු {amount}",
    cart_history_items: "{n} භාණ්ඩ",
    // Chat suggestions
    chat_suggested: "යෝජනා",
    suggestion_add_chocolates: "චොකලට් එකතු කරන්න",
    suggestion_add_flowers: "මල් එකතු කරන්න",
    suggestion_add_cake: "කේක් එකතු කරන්න",
    suggestion_gift_wrap: "{occasion} සඳහා තෑගි ඔතන්න",
    suggestion_cut_budget: "රු {amount} ට කපන්න",
    suggestion_upgrade_premium: "ප්‍රිමියම් රු {amount}",
    suggestion_same_day: "දිනූ දිනෙම බෙදාහැරීම",
    suggestion_change_city: "{city} ට යවන්න",
    suggestion_rebuild: "කරත්තය නැවත සාදන්න",
    // Profile order fields
    order_recipient: "ලබන්නා",
    order_city: "නගරය",
    order_date: "දිනය",
    order_total: "එකතුව",
    // Checkout validation messages
    checkout_sender_required: "යවන්නාගේ නම අවශ්‍යයි",
    checkout_recipient_required: "ලබන්නාගේ නම අවශ්‍යයි",
    checkout_phone_required: "ජංගම දුරකථනය අවශ්‍යයි",
    checkout_phone_invalid: "වලංගු ශ්‍රී ලංකා දුරකථන අංකයක් ඇතුළත් කරන්න",
    checkout_email_invalid: "වලංගු ඊමේල් ලිපිනයක් ඇතුළත් කරන්න",
    checkout_city_required: "බෙදාහරින නගරය අවශ්‍යයි",
    checkout_date_required: "කැමති දිනය අවශ්‍යයි",
    checkout_date_past: "අනාගත දිනයක් තෝරන්න",
    checkout_cart_empty: "ඔබගේ කරත්තය හිස්ය",
    checkout_price_changed: "සමහර භාණ්ඩවල මිල වෙනස් වී ඇත — කරත්තය නැවත පරීක්ෂා කරන්න.",
    checkout_item_unavailable: "සමහර භාණ්ඩ දැන් ලබා ගත නොහැක.",
    checkout_processing: "ඇණවුම සකසමින්…",
    checkout_order_confirmed: "ඇණවුම තහවුරුයි!",
    checkout_save_ref: "ඔබගේ ඇණවුම් යොමු අංකය සුරකින්න",
    checkout_track_order: "Kapruka.com හි නිරීක්ෂණය",
    checkout_payment_failed: "ගෙවීම අසාර්ථකයි. කරත්තය සුරකින ලදී — නැවත උත්සාහ කරන්න.",
    checkout_duplicate_prevented: "ඔබගේ ඇණවුම දැනටමත් සකසමින් ඇත.",
    // Pluralization
    cart_item_count_one: "{n} භාණ්ඩය",
    cart_item_count_many: "{n} භාණ්ඩ",
    cart_empty: "ඔබගේ කරත්තය හිස්ය",
    // ── Gaps & Localization additions ───────────────────────────────
    ai_pick: "✨ AI තේරීම",
    for_recipient: " {recipient} සඳහා",
    within_budget: " රු. {budget} සීමාව තුළ",
    ruka_greeting_curated: "මම {recipient} වෙනුවෙන් {occasion} සඳහා {budget} සීමාව තුළ ඇති හොඳම {categories} සැලැස්ම සකස් කළෙමි. 🎁 වෙනත් සැලසුම් තෝරාගැනීමට හෝ මගෙන් ඕනෑම දෙයක් අසන්න!",
    ruka_greeting_prompt: "LKR {budget} සීමාව තුළ \"{prompt}\" සඳහා ඔබ වෙනුවෙන් සකසන ලද කරත්තය මෙන්න. වෙනස් කිරීමට යමක් තිබේද?",
    // Category labels
    category_flowers: "මල්",
    category_cakes: "කේක්",
    category_groceries: "බඩු බාහිරාදිය",
    category_chocolates: "චොකලට්",
    category_toys: "සෙල්ලම් බඩු",
    category_gifts: "තෑගි",
    category_hampers: "හෑම්පර්ස්",
    category_books: "පොත්",
    category_electronics: "විද්‍යුත් උපකරණ",
    category_clothing: "ඇඳුම් පැළඳුම්",
    category_cosmetics: "සුවඳ විලවුන්",
    // DNA chips: Occasions
    dna_occasion_birthday: "උපන්දිනය",
    dna_occasion_anniversary: "සංවත්සරය",
    dna_occasion_wedding: "මංගල උත්සවය",
    dna_occasion_valentine: "පෙම්වතුන්ගේ දිනය",
    dna_occasion_mothers_day: "මව්වරුන්ගේ දිනය",
    dna_occasion_fathers_day: "පියවරුන්ගේ දිනය",
    dna_occasion_christmas: "නත්තල",
    dna_occasion_new_year: "අලුත් අවුරුද්ද",
    dna_occasion_graduation: "උපාධි ප්‍රදානය",
    dna_occasion_farewell: "සමුගැනීම",
    dna_occasion_get_well: "සුවදුක් විමසීම",
    dna_occasion_thank_you: "ස්තූතියි",
    // DNA chips: Recipients
    dna_recipient_amma: "අම්මාට",
    dna_recipient_mother: "මවට",
    dna_recipient_father: "තාත්තාට",
    dna_recipient_thaththa: "තාත්තාට",
    dna_recipient_sister: "සහෝදරියට",
    dna_recipient_brother: "සහෝදරයාට",
    dna_recipient_friend: "මිතුරාට",
    dna_recipient_colleague: "සගයාට",
    dna_recipient_teacher: "ගුරුවරයාට",
    dna_recipient_girlfriend: "පෙම්වතියට",
    dna_recipient_boyfriend: "පෙම්වතාට",
    dna_recipient_partner: "සහකරුට",
    dna_recipient_baby: "බබාට",
    dna_recipient_kids: "ළමුන්ට",
    dna_recipient_grandma: "ආච්චිට",
    dna_recipient_grandfather: "සීයාට",
    // DNA chips: Sentiments
    dna_sentiment_heartfelt: "හදවතින්ම",
    dna_sentiment_premium: "ප්‍රමුඛ",
    dna_sentiment_luxury: "සුඛෝපභෝගී",
    dna_sentiment_budget: "ලාභදායී තේරීම",
    dna_sentiment_popular: "ජනප්‍රිය",
    dna_sentiment_fresh: "නැවුම්",
    dna_sentiment_classic: "සම්භාව්‍ය",
    dna_sentiment_surprise: "පුදුම කිරීමක්",
    dna_sentiment_romantic: "රොමැන්ටික්",
    dna_sentiment_healthy: "සෞඛ්‍ය සම්පන්න",
    dna_sentiment_traditional: "සාම්ප්‍රදායික",
    dna_sentiment_best_seller: "වැඩිපුරම අලෙවි වන",
    dna_sentiment_handpicked: "තෝරාගත්"
  },
  "en-LK": {
    search_placeholder: "Search products…",
    active_crate: "Active Crate eka",
    login: "Login wenna",
    logout: "Logout wenna",
    all_categories: "☰ All Categories",
    for_you: "Oyaata wage",
    ideal_plan: "Ideal Plan eka",
    cheaper: "Adu ganan",
    premium: "Premium eka",
    fast_delivery: "Ikmanata deliver",
    empty_crate: "Crate eka empty",
    empty_crate_sub: "Mee shopping flow eke items mukuth nehe.",
    alternative_discoveries: "Alternative choices",
    curation_crate_story: "AI Curation Story eka",
    crate_evolution_timeline: "Cart History",
    continue_cart: "Cart eka continue karanna",
    profile_title: "Your account",
    profile_orders: "Order history",
    profile_bookmarks: "Saved products",
    profile_no_orders: "No orders yet — checkout once to see them here.",
    profile_no_bookmarks: "Tap ★ on a product card to save it.",
    profile_start_shopping: "Start shopping",
    profile_orders_count: "Orders",
    profile_bookmarks_count: "Saved",
    profile_logout: "Sign out",
    profile_refresh: "Refresh",
    profile_order_guest: "Guest checkout",
    profile_order_live: "Kapruka order",
    profile_order_sim: "Demo order",
    profile_saved_on: "Saved",
    profile_remove_bookmark: "Remove",
    profile_ruka_tab: "For Ruka",
    profile_ruka_title: "What Ruka remembers",
    profile_ruka_desc: "This shapes city defaults, budget hints, and product ranking when you build a cart.",
    profile_ruka_empty: "Sign in and shop once — Ruka will remember your city, budget, and saved items.",
    profile_ruka_orders: "Uses {count} past order(s) for category and budget hints.",
    profile_ruka_city: "Usually delivers to {city}.",
    profile_ruka_budget: "Typical spend around LKR {budget}.",
    profile_ruka_categories: "Favourite categories: {cats}.",
    profile_ruka_saved: "Boosts {count} saved product(s) in cart picks.",
    profile_ruka_build: "Build cart with my profile",
    profile_reorder: "Reorder with Ruka",
    out_of_stock: "Out of stock",
    out_of_stock_cart_hint: "Checkout ekata pera out-of-stock items remove karanna.",
    checkout_stock_error: "Cart eke product ekak out of stock. Remove karala try again karanna.",
    rollback_note: "* Click on any step to go back to that rollback point.",
    budget_meter: "Budget Meter eka",
    over_budget: "Budget limit panala",
    healthy: "Shape",
    drag_to_adjust: "Budget Limit adjust karanna slide karanna",
    items_subtotal: "Items subtotal eka",
    delivery_fee: "Delivery fee eka",
    total_price: "Total price eka",
    proceed_to_checkout: "Checkout wenna",
    control_center: "Control Center eka",
    curation_actions: "AI Curation Actions",
    personalization_delivery: "Personalization & Delivery",
    language_context: "Language details",
    make_cheaper: "Price adu karanna",
    upgrade_premium: "Premium upgrade karන්න",
    today_delivery: "Ada deliver karන්න",
    gift_mode: "Gift mode danna",
    sinhala: "Sinhala karanna",
    tanglish: "Tanglish karanna",
    optimize: "Optimize karන්න",
    surprise_me: "Surprise me!",
    remove: "Remove karanna",
    replace: "Replace karanna",
    qty: "Qty",
    curation_note: "Curation Note eka",
    add_to_crate: "Add to Crate eka +",
    search_catalog: "Catalog eke search karanna...",
    alternative_items: "Wena items:",
    searching_catalog: "Search wenawa...",
    no_items_found: "Items hambune nehe",
    review_checkout: "Review karලා Checkout wenna",
    checkout_sub: "Kapruka guest order ekak hadanna. Account one nehe.",
    sender_details: "1. Oyaage Details",
    your_full_name: "Oyaage Name eka",
    recipient_details: "2. Recipient Details",
    name: "Name eka",
    mobile_phone: "Phone number eka",
    delivery_gift_msg: "3. Delivery & Gift Message eka",
    delivery_city: "Delivery City eka",
    preferred_date: "Delivery Date eka",
    street_address: "Address eka",
    instructions_opt: "Instructions (Optional)",
    gift_card_msg_opt: "Gift Message (Optional)",
    total_with_delivery: "Total eka (with delivery)",
    cancel: "Cancel",
    proceed_to_payment: "Continue to Payment",
    generating_secure_checkout: "Secure checkout link hadenawa…",
    preparing_order: "Order eka ready wenawa...",
    order_success: "Order eka success!",
    order_success_sub: "Oyaage guest order eka Kapruka eke register una.",
    invoice_title: "Kapruka Flow Receipt eka",
    order_ref: "Order Ref eka:",
    date: "Date eka:",
    sender: "Sender:",
    recipient: "Recipient:",
    phone: "Phone eka:",
    city: "City eka:",
    deliver_to: "Deliver To:",
    item_description: "Item Description eka",
    qty_header: "Qty",
    total_header: "Total",
    final_total: "Final Total eka:",
    simulated_checkout_note: "Simulation check out eka generate una.",
    complete_payment: "Kapruka eke pay karanna",
    close_return: "Close karලා yanna",
    guest_user: "Guest User",
    alert_no_crate: "Active curation crate ekak hambune nehe. Kalin prompt ekak type karala start karanna!",
    curation_in_progress: "AI eka curate karanawa...",
    step_understanding: "Understand wenawa",
    step_finding: "Search wenawa",
    step_budget: "Budget and Price planning",
    step_delivery: "Delivery verify karanawa",
    step_cart: "Cart eka complete karanawa",
    starting: "Start wenawa",
    compiled: "Ready una",
    ready: "Ready",
    mcp_live: "Kapruka MCP live",
    mcp_connecting: "Kapruka MCP ekata connect wenawa...",
    mcp_status_ready: "Ready",
    mcp_status_connecting: "Connecting",
    mcp_status_live: "Live",
    mcp_status_unavailable: "Unavailable",
    mcp_demo_still_available: "Demo eka thiyenawa",
    waiting_pipeline: "AI shopping plan eka run wenawa...",
    header_tagline: "Oyaata onee de kiyanna. Api plan eka hadanawa.",
    new_flow: "New Flow",
    plan_changes: "Plan Changes",
    added: "Add una",
    removed: "Remove una",
    checkout_failed: "Order create karanna ba",
    checkout_failed_sub: "Kapruka order eka create karanna ba. Delivery city, date, products check karanna.",
    pipeline_error: "Shopping flow build karanna ba. Try again karanna.",
    pipeline_timeout: "Request timeout una — MCP slow wela thiyenawa. Try again.",
    network_fail: "Network error — connection eka check karala try again karanna.",
    no_products: "Kisima matching product ekak labune natha. Cakes, chocolates, flowers, grocery vage suggestions ekak use karala rephrase karanna.",
    suggested_addons: "Suggested add-ons",
    suggested_addons_hint: "Thawa ona da? Methanin kamati ewa add karanna — price eka wadi unath adu unath. Budget eka exceed unath, oyaage decision.",
    lower_price: "Adu mila",
    higher_price: "Wadi mila",
    over_budget_hint: "Oya budget eka exceed kara. Item ekak remove karanna, adu mila suggestion ekak daanna, naththan slider eka wadi karanna. Oyaage call eka.",
    chat_placeholder: "Mokakda change karanna ona kiyala Ruka ta kiyanna (e.g. 'add chocolates', 'make it cheaper')…",
    qr_add_choc: "Chocolate add karanna",
    qr_add_flowers: "Flowers add karanna",
    qr_add_cake: "Cake add karanna",
    qr_add_groceries: "Groceries add karanna",
    chat_reply_cheaper: "Hari, value-focused plan ekata maaru kala. 💸",
    chat_reply_premium: "Mehema thiyenne richer mix ekak ekka premium plan eka. ✨",
    chat_reply_fast: "Wegawathma delivery plan ekata maaru kala. ⚡",
    chat_reply_budget: "Okkoma LKR {budget} ekata fit wenna re-balance kala. ✅",
    chat_reply_city: "Delivery eka {city} ekata update kala. 🚚",
    chat_reply_added: "{name} oyaage cart ekata add kala. 🛒",
    chat_reply_add_fail: "'{query}' dan Kapruka catalog eke hoyaganna nehe. Wena item ekak try karamuda?",
    chat_reply_removed: "{name} remove kala. 👍",
    chat_reply_remove_fail: "Oyaage cart eke '{query}' hoyaganna nehe. Mona item ekada remove karanne?",
    chat_reply_gift: "Hari, meka gift ekak widihata gannam. 🎁",
    chat_reply_researching: "Kapruka catalog eken eka hoyala balannam…",
    chat_reply_reorder: "Oya order history eken rebuild karanawa…",
    chat_reply_saved_added: "Oya saved items add kala: {names}. ★",
    chat_reply_saved_none: "Saved items thiyenne nehe — product card eke ★ tap karanna.",
    agent_profile_note: "Oya profile ({summary}) use karala picks personalize kala.",
    agent_profile_orders: "{count} past orders",
    agent_profile_saved: "{count} saved items",
    agent_profile_city: "usually {city}",
    qr_reorder: "Reorder favourites",
    qr_add_saved: "Saved items add karanna",
    qr_deliver_city: "{city} ekata deliver karanna",
    insight_orders: "{count} orders",
    insight_saved: "{count} saved",
    insight_usual_city: "Usually {city}",
    chat_clarify: "Mama budget eka change karanna, plan maaru karanna, item add/remove karanna, naththan delivery change karanna puluwan. 'add chocolates under 3000', 'make it cheaper', naththan 'deliver to Galle' try karanna.",
    mcp_tools_title: "Use kala Kapruka MCP tools",
    mcp_calls: "calls",
    run_demo: "▶ Run Demo",
    picked_for_you: "Oya wenuwen",
    demo_hint: "Aluth da? Ruka seconds keepayakin gift ekak plan karanawa balanna tap karanna.",
    agent_name: "Ruka",
    agent_role: "Oyaage Kapruka shopping buddy",
    agent_greeting: "Hari, mama Ruka 🌸 oyaage personal Kapruka shopper. Kaatada, budget eka kiyada kiyanna, mama Kapruka live catalog eken best cart eka hadannam.",
    agent_reply_intro: "Set! Kapruka live catalog eken mama hadapu eka mehema 👇",
    agent_budget_inferred: "Oya budget ekak dunne nehe, ehema nisa LKR {budget} ක් gaththa. Slider eka adala, mama wahama re-balance karannam. Real limit eka kiyada?",
    agent_gift_note: "Meka gift ekak wage{recipient}, ehema nisa eyalata kamati ewa select kala. 🎁",
    agent_occasion_note: "Suba {occasion}! Occasion ekata tune kala. 🎉",
    agent_pick_one: "Plan ekak select karanna (Ideal, Cheaper, Premium hari Fast), mama oyawa keliyenma checkout ekata geniyannam. 🛒",
    agent_thinking: "Ruka hithanawa…",
    flow_error_title: "Mokak hari wela",
    dismiss: "Close karanna",
    share_flow: "Flow eka share karanna",
    link_copied: "Link copy una!",
    view_on_kapruka: "Kapruka eke balanna",
    mcp_catalog_count: "Kapruka MCP Catalog",
    products_live: "live products",
    order_ref_note: "Me checkout reference eka. Browser eke pay karapu passe order number email ekata enawa.",
    powered_by_mcp: "Kapruka MCP through order create una",
    email_optional: "Email (optional)",
    create_account_opt: "Mage Kapruka Flow account eka hadanna, order eka track karanna (optional)",
    choose_password: "Password ekak select karanna",
    
    // Intent Canvas additions
    intelligent_ai_curation: "Intelligent AI Curation eka",
    what_do_you_want: "Oyaata onee de kiyanna.",
    what_do_you_want_line2: "Mama cart eka hadannam.",
    intent_desc: "Oyaage shopping goal eka describe karanna. Api perfect cart ekak compose karanawa.",
    build_my_cart: "Build My Cart",
    voice_intent: "Voice intent eka",
    listening: "Ahagena inne...",
    input_placeholder: "Mata tea bags 5000 ta aduwen heta wenakota deliver karanna...",
    compose: "Compose karanna",
    quick_suggestions: "Quick suggestions",
    search_btn: "Search",
    account_label: "Account",
    hello_label: "Hello",
    trending: "Trending",
    live_badge: "Live",
    reset_label: "Reset",
    browse_categories: "Kapruka categories balanna",
    loading: "Loading…",
    cart_item_singular: "item",
    cart_item_plural: "items",
    welcome_back: "Welcome back",
    history_note: "AI oyaage order history use karanawa",
    try_again: "Try again",
    general_category: "General",
    lang_english: "English",
    lang_sinhala: "සිංහල (Sinhala)",
    lang_tanglish: "Tanglish (Sri Lanka)",
    qs_monthly_label: "Monthly shopping",
    qs_monthly_text: "groceries 20000 ta adu LKR",
    qs_today_label: "Ada onee de",
    qs_today_text: "Ada Colombo ekata groceries deliver karanna onee",
    qs_gift_label: "Gift crate",
    qs_gift_text: "Nangi graduate una, 15000 ta adu gift hamper ekak",
    qs_surprise_label: "Surprise me",
    qs_surprise_text: "Tea saha cake hamper ekakin surprise karanna",
    qs_build_label: "Cart hadanna",
    qs_build_text: "Team ekata tea time snacks cart ekak hadanna",
    qs_budget_label: "Budget shopping",
    qs_budget_text: "10000 ta adu dinner budget shopping",
    qs_custom_label: "Custom request",
    qs_custom_text: "Fresh fruits saha chocolates custom request",
    mcp_tool_search: "Product search",
    mcp_tool_details: "Product details",
    mcp_tool_cities: "Delivery cities",
    mcp_tool_delivery: "Delivery check",
    mcp_tool_categories: "Categories",
    mcp_tool_order: "Order creation",
    ai_insights_title: "AI Insights",
    detected_intent: "Detected intent",
    insight_budget: "Budget",
    insight_remaining: "Remaining",
    insight_delivery_today: "Tomorrow",
    insight_delivery_fast: "Fast",
    insight_delivery_standard: "Standard",
    // Cart history & budget meter
    compare_versions: "⚖️ Versions Compare Karanna",
    budget_spent: "{amount} use kala",
    budget_limit_label: "Limit {amount}",
    step_label: "Step {n}",
    step_current: "(Now)",
    cart_history_spent: "Spent: Rs {amount}",
    cart_history_items: "{n} items",
    // Chat suggestions
    chat_suggested: "Suggestions",
    suggestion_add_chocolates: "Chocolate add karanna",
    suggestion_add_flowers: "Flowers add karanna",
    suggestion_add_cake: "Cake ekak add karanna",
    suggestion_gift_wrap: "{occasion} ekata gift wrap karanna",
    suggestion_cut_budget: "Rs {amount} ta cut karanna",
    suggestion_upgrade_premium: "Premium Rs {amount}",
    suggestion_same_day: "Ada deliver karanna",
    suggestion_change_city: "{city} ekata yavanna",
    suggestion_rebuild: "Cart eka rebuild karanna",
    // Profile order fields
    order_recipient: "Recipient",
    order_city: "City eka",
    order_date: "Date eka",
    order_total: "Total eka",
    // Checkout validation messages
    checkout_sender_required: "Oyaage name eka required",
    checkout_recipient_required: "Recipient name eka required",
    checkout_phone_required: "Phone number eka required",
    checkout_phone_invalid: "Valid Sri Lanka phone number ekak denna (07xxxxxxxx)",
    checkout_email_invalid: "Valid email ekak denna",
    checkout_city_required: "Delivery city eka required",
    checkout_date_required: "Delivery date eka required",
    checkout_date_past: "Future date ekak select karanna",
    checkout_cart_empty: "Cart eka empty",
    checkout_price_changed: "Kisi items ge mila wenas wela — cart eka check karanna.",
    checkout_item_unavailable: "Kisi items available nehe.",
    checkout_processing: "Order eka process wenawa…",
    checkout_order_confirmed: "Order Confirmed!",
    checkout_save_ref: "Order reference eka save karanna",
    checkout_track_order: "Kapruka.com eke track karanna",
    checkout_payment_failed: "Payment una nehe. Cart eka save una — try again karanna.",
    checkout_duplicate_prevented: "Order eka already process wenawa.",
    // Pluralization
    cart_item_count_one: "{n} item",
    cart_item_count_many: "{n} items",
    cart_empty: "Cart eka empty",
    // ── Gaps & Localization additions ───────────────────────────────
    ai_pick: "✨ AI Pick",
    for_recipient: " {recipient} ta",
    within_budget: " LKR {budget} budget ekata",
    ruka_greeting_curated: "Mama {recipient} ta {occasion} ekata {budget} budget ekata perfect {categories} compose kala. 🎁 Switch plans or ask me anything!",
    ruka_greeting_prompt: "LKR {budget} budget ekata \"{prompt}\" curated cart eka methana thiyenawa. Anything to tweak?",
    // Category labels
    category_flowers: "Flowers",
    category_cakes: "Cakes",
    category_groceries: "Groceries",
    category_chocolates: "Chocolates",
    category_toys: "Toys",
    category_gifts: "Gifts",
    category_hampers: "Hampers",
    category_books: "Books",
    category_electronics: "Electronics",
    category_clothing: "Clothing",
    category_cosmetics: "Cosmetics",
    // DNA chips: Occasions
    dna_occasion_birthday: "Birthday",
    dna_occasion_anniversary: "Anniversary",
    dna_occasion_wedding: "Wedding",
    dna_occasion_valentine: "Valentine's",
    dna_occasion_mothers_day: "Mother's Day",
    dna_occasion_fathers_day: "Father's Day",
    dna_occasion_christmas: "Christmas",
    dna_occasion_new_year: "New Year",
    dna_occasion_graduation: "Graduation",
    dna_occasion_farewell: "Farewell",
    dna_occasion_get_well: "Get Well",
    dna_occasion_thank_you: "Thank You",
    // DNA chips: Recipients
    dna_recipient_amma: "Amma ta",
    dna_recipient_mother: "Mother ta",
    dna_recipient_father: "Father ta",
    dna_recipient_thaththa: "Thaththa ta",
    dna_recipient_sister: "Sister ta",
    dna_recipient_brother: "Brother ta",
    dna_recipient_friend: "Friend ta",
    dna_recipient_colleague: "Colleague ta",
    dna_recipient_teacher: "Teacher ta",
    dna_recipient_girlfriend: "GF ta",
    dna_recipient_boyfriend: "BF ta",
    dna_recipient_partner: "Partner ta",
    dna_recipient_baby: "Baby ta",
    dna_recipient_kids: "Kids ta",
    dna_recipient_grandma: "Grandma ta",
    dna_recipient_grandfather: "Grandpa ta",
    // DNA chips: Sentiments
    dna_sentiment_heartfelt: "Heartfelt",
    dna_sentiment_premium: "Premium",
    dna_sentiment_luxury: "Luxury",
    dna_sentiment_budget: "Value Pick",
    dna_sentiment_popular: "Popular",
    dna_sentiment_fresh: "Fresh",
    dna_sentiment_classic: "Classic",
    dna_sentiment_surprise: "Surprise",
    dna_sentiment_romantic: "Romantic",
    dna_sentiment_healthy: "Healthy",
    dna_sentiment_traditional: "Traditional",
    dna_sentiment_best_seller: "Best Seller",
    dna_sentiment_handpicked: "Handpicked"
  }
};

const QUICK_SUGGESTION_KEYS = [
  ["qs_monthly_label", "qs_monthly_text"],
  ["qs_today_label", "qs_today_text"],
  ["qs_gift_label", "qs_gift_text"],
  ["qs_surprise_label", "qs_surprise_text"],
  ["qs_build_label", "qs_build_text"],
  ["qs_budget_label", "qs_budget_text"],
  ["qs_custom_label", "qs_custom_text"],
];

export function getQuickSuggestions(lang = "en-US") {
  const s = LOCALIZED_STRINGS[lang] || LOCALIZED_STRINGS["en-US"];
  return QUICK_SUGGESTION_KEYS.map(([labelKey, textKey]) => ({
    label: s[labelKey] || labelKey,
    text: s[textKey] || "",
  }));
}

const MCP_TOOL_STRING_KEYS = {
  kapruka_search_products: "mcp_tool_search",
  kapruka_get_product: "mcp_tool_details",
  kapruka_list_delivery_cities: "mcp_tool_cities",
  kapruka_check_delivery: "mcp_tool_delivery",
  kapruka_list_categories: "mcp_tool_categories",
  kapruka_create_order: "mcp_tool_order",
};

export function getMcpToolLabel(toolName, strings = {}) {
  const key = MCP_TOOL_STRING_KEYS[toolName];
  if (key && strings[key]) return strings[key];
  return toolName?.replace(/^kapruka_/, "").replace(/_/g, " ") || toolName;
}

export function getMcpStatusPresentation(status, strings = {}) {
  switch (status) {
    case "connecting":
      return {
        label: strings.mcp_status_connecting || "Connecting",
        dotClass: "mcp-dot-connecting",
      };
    case "live":
      return {
        label: strings.mcp_status_live || "Live",
        dotClass: "mcp-dot-live",
      };
    case "unavailable":
      return {
        label: strings.mcp_status_unavailable || "Unavailable",
        dotClass: "mcp-dot-unavailable",
        hint: strings.mcp_demo_still_available || "Demo still available",
      };
    default:
      return {
        label: strings.mcp_status_ready || "Ready",
        dotClass: "mcp-dot-ready",
      };
  }
}
